# Generated by Django 3.2.13 on 2022-04-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('workspace', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_workspace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'workspace',
                'managed': False,
            },
        ),
    ]
