# Generated by Django 3.2.13 on 2022-04-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.IntegerField(blank=True, null=True)),
                ('dataset', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workspace_dataset',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DatasetPermission',
        ),
    ]
